version: '3.8'

services:
  postgres:
    container_name: pgdb
    restart: always
    image: postgres:14-alpine
    volumes:
      - ./pgdb:/var/lib/postgresql/data
      - ./create_container_database.sql:/docker-entrypoint-initdb.d/create_container_database.sql
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=root
    ports:
      - 5432:5432