version: '3.8'

services:
  postgres:
    container_name: pgdb
    restart: always
    image: postgres:14-alpine
    volumes:
      - ./pgdb:/var/lib/postgresql/data
      - ./create_container_database.sql:/docker-entrypoint-initdb.d/create_container_database.sql
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=root
    networks:
      - backend
    
  next-notes:
    container_name: next-notes-crud
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
    driver: bridge